SUPPORTED_COMMANDS = [
    "get_fsm_id",
    "get_fsm_mode",
    "get_balance_mode",
    "get_swing_height",
    "get_stand_height",
    "get_phase",
    "set_fsm_id",
    "set_balance_mode",
    "set_swing_height",
    "set_stand_height",
    "set_velocity",
    "damp",
    "start",
    "squat",
    "sit",
    "stand_up",
    "zero_torque",
    "stop_move",
    "high_stand",
    "low_stand",
    "balance_stand",
    "continous_gait",
    "switch_move_mode",
    "move",
    "set_task_id",
    "shake_hand",
    "wave_hand",
    "wave_hand_with_turn",
    "set_speed_mode",
]


REQUIRES_PARAM = {
    "set_velocity",
    "set_stand_height",
    "set_swing_height",
    "set_fsm_id",
    "set_balance_mode",
    "set_task_id",
    "set_speed_mode",
    "move",
}
